# Datasource Oracle
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=${ORACLE_USER}
quarkus.datasource.password=${ORACLE_PASS}
quarkus.datasource.jdbc.url=${ORACLE_URL}

# Integracao Python (placeholder — client implementado na Etapa 4)
api.python.base-url=${API_PYTHON_BASE_URL:}

quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:10000}