-- =============================================================
-- PROJETO NORA - PARTE JAVA
-- Disciplina: Java / Backend - FIAP ADS
-- Script: criacao de tabelas, constraints, dados iniciais e consultas
-- Banco: Oracle
-- Execucao: SQL Developer ou sqlplus
--
-- Objetivo:
-- Base real do banco Oracle para a Etapa 2 do Projeto Java Nora:
-- banco, entities, DAOs, regras obrigatorias de negocio,
-- persistencia JDBC manual, testes manuais e entrega academica.
--
-- Observacao:
-- Este DDL segue o padrao academico do script Python do Projeto Nora,
-- mas amplia o dominio para atender o backend Java.
-- =============================================================


-- =============================================================
-- DROP DAS TABELAS
-- Ordem inversa das FKs
-- =============================================================

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TB_ACOMP_EVENTO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TB_MENSAGEM CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TB_CONVERSA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TB_ENCAMINHAMENTO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TB_DENTISTA_ESPECIALIDADE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TB_PACIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TB_TRIAGEM CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TB_PESSOA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TB_COLABORADOR_SESSAO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TB_COLABORADOR CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TB_ESPECIALIDADE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TB_DENTISTA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TB_ENDERECO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/


-- =============================================================
-- CREATE TB_ENDERECO
-- Enderecos de pessoas e dentistas.
-- Latitude/longitude sao opcionais para cenarios com geocodificacao.
-- =============================================================

CREATE TABLE TB_ENDERECO (
                             ID_ENDERECO     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             CEP             VARCHAR2(8)   NOT NULL,
                             LOGRADOURO      VARCHAR2(150) NOT NULL,
                             NUMERO          VARCHAR2(15)  NOT NULL,
                             COMPLEMENTO     VARCHAR2(60),
                             BAIRRO          VARCHAR2(80)  NOT NULL,
                             CIDADE          VARCHAR2(80)  NOT NULL,
                             UF              VARCHAR2(2)   NOT NULL,
                             LATITUDE        NUMBER(10,7),
                             LONGITUDE       NUMBER(10,7),
                             DATA_CRIACAO    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                             CONSTRAINT CHK_END_CEP CHECK (LENGTH(CEP) = 8),
                             CONSTRAINT CHK_END_UF CHECK (LENGTH(UF) = 2)
);


-- =============================================================
-- CREATE TB_COLABORADOR
-- Funcionarios internos para login e operacao do sistema.
-- Senha armazenada como hash/texto tecnico para ambiente academico.
-- =============================================================

CREATE TABLE TB_COLABORADOR (
                                ID_COLABORADOR  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                NOME            VARCHAR2(120) NOT NULL,
                                EMAIL           VARCHAR2(120) NOT NULL UNIQUE,
                                SENHA_HASH      VARCHAR2(255) NOT NULL,
                                PERFIL          VARCHAR2(20)  DEFAULT 'atendente' NOT NULL,
                                STATUS_COLAB    VARCHAR2(10)  DEFAULT 'ativo' NOT NULL,
                                DATA_CRIACAO    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                                CONSTRAINT CHK_COLAB_PERFIL CHECK (PERFIL IN ('admin','atendente','gestor')),
                                CONSTRAINT CHK_COLAB_STATUS CHECK (STATUS_COLAB IN ('ativo','inativo'))
);


-- =============================================================
-- CREATE TB_COLABORADOR_SESSAO
-- Controle simples de sessao/token opaco.
-- Alternativa academica mais simples do que JWT completo.
-- =============================================================

CREATE TABLE TB_COLABORADOR_SESSAO (
                                       ID_SESSAO       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       ID_COLABORADOR  NUMBER NOT NULL,
                                       TOKEN           VARCHAR2(120) NOT NULL UNIQUE,
                                       DATA_CRIACAO    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                                       DATA_EXPIRACAO  TIMESTAMP NOT NULL,
                                       STATUS_SESSAO   VARCHAR2(10) DEFAULT 'ativo' NOT NULL,

                                       CONSTRAINT FK_SESSAO_COLAB FOREIGN KEY (ID_COLABORADOR)
                                           REFERENCES TB_COLABORADOR(ID_COLABORADOR),

                                       CONSTRAINT CHK_SESSAO_STATUS CHECK (STATUS_SESSAO IN ('ativo','inativo','expirada'))
);


-- =============================================================
-- CREATE TB_PESSOA
-- Lead/cadastro inicial vindo do bot, N8N, frontend ou cadastro manual.
-- Regra de negocio: Projeto Nora atende adolescentes de 11 a 17 anos.
-- =============================================================

CREATE TABLE TB_PESSOA (
                           ID_PESSOA       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           ID_ENDERECO     NUMBER NOT NULL,
                           NOME_COMPLETO   VARCHAR2(120) NOT NULL,
                           CPF             VARCHAR2(11) UNIQUE,
                           DATA_NASCIMENTO DATE NOT NULL,
                           IDADE           NUMBER(3) NOT NULL,
                           SEXO            VARCHAR2(1),
                           EMAIL           VARCHAR2(120),
                           TELEFONE        VARCHAR2(20) NOT NULL,
                           TG_CHAT_ID      VARCHAR2(80),
                           CANAL_ORIG      VARCHAR2(20) DEFAULT 'telegram' NOT NULL,
                           STTS_PESS       VARCHAR2(20) DEFAULT 'lead' NOT NULL,
                           DATA_CRIACAO    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                           DATA_ATUALIZACAO TIMESTAMP,

                           CONSTRAINT FK_PESS_END FOREIGN KEY (ID_ENDERECO)
                               REFERENCES TB_ENDERECO(ID_ENDERECO),

                           CONSTRAINT CHK_PESS_IDADE CHECK (IDADE BETWEEN 11 AND 17),
                           CONSTRAINT CHK_PESS_SEXO CHECK (SEXO IS NULL OR SEXO IN ('M','F','O')),
                           CONSTRAINT CHK_PESS_CANAL CHECK (CANAL_ORIG IN ('telegram','web','manual','n8n')),
                           CONSTRAINT CHK_PESS_STATUS CHECK (STTS_PESS IN ('lead','em_triagem','aprovada','reprovada','inativa'))
);


-- =============================================================
-- CREATE TB_TRIAGEM
-- Avaliacao de elegibilidade, urgencia e prioridade.
-- Campos NIVEL_URG_IA e CONF_IA sustentam integracao com Python/ML.
-- =============================================================

CREATE TABLE TB_TRIAGEM (
                            ID_TRIAGEM      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ID_PESSOA       NUMBER NOT NULL,
                            IDADE           NUMBER(3) NOT NULL,
                            ELEG_TRIAG      VARCHAR2(12) NOT NULL,
                            PRIOR_TRIAG     VARCHAR2(10) NOT NULL,
                            SEXO_PESS       VARCHAR2(1),
                            PROBLEMA_BUCAL  VARCHAR2(300) NOT NULL,
                            RENDA_FAMILIAR  VARCHAR2(20) NOT NULL,
                            NIVEL_URG_IA    NUMBER(3,1),
                            CONF_IA         NUMBER(5,2),
                            STTS_TRIAG      VARCHAR2(15) DEFAULT 'em_analise' NOT NULL,
                            DECISAO         VARCHAR2(15) DEFAULT 'pendente' NOT NULL,
                            OBSERVACOES     VARCHAR2(300),
                            DATA_CRIACAO    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                            DATA_ATUALIZACAO TIMESTAMP,

                            CONSTRAINT FK_TRIAG_PESS FOREIGN KEY (ID_PESSOA)
                                REFERENCES TB_PESSOA(ID_PESSOA),

                            CONSTRAINT CHK_TRIAG_IDADE CHECK (IDADE BETWEEN 11 AND 17),
                            CONSTRAINT CHK_TRIAG_ELEG CHECK (ELEG_TRIAG IN ('elegivel','inelegivel')),
                            CONSTRAINT CHK_TRIAG_PRIOR CHECK (PRIOR_TRIAG IN ('baixa','media','alta','urgente')),
                            CONSTRAINT CHK_TRIAG_SEXO CHECK (SEXO_PESS IS NULL OR SEXO_PESS IN ('M','F','O')),
                            CONSTRAINT CHK_TRIAG_RENDA CHECK (RENDA_FAMILIAR IN ('ate_1sm','1_3sm','acima_3sm','nao_informada')),
                            CONSTRAINT CHK_TRIAG_IA CHECK (NIVEL_URG_IA IS NULL OR NIVEL_URG_IA BETWEEN 0 AND 5),
                            CONSTRAINT CHK_TRIAG_CONF CHECK (CONF_IA IS NULL OR CONF_IA BETWEEN 0 AND 100),
                            CONSTRAINT CHK_TRIAG_STATUS CHECK (STTS_TRIAG IN ('em_analise','aprovada','reprovada','cancelada')),
                            CONSTRAINT CHK_TRIAG_DEC CHECK (DECISAO IN ('pendente','aprovado','reprovado','cancelado'))
);


-- =============================================================
-- CREATE TB_PACIENTE
-- Pessoa aprovada na triagem e apta a receber encaminhamento.
-- =============================================================

CREATE TABLE TB_PACIENTE (
                             ID_PACIENTE     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             ID_PESSOA       NUMBER NOT NULL UNIQUE,
                             ID_TRIAGEM      NUMBER NOT NULL UNIQUE,
                             IDADE           NUMBER(3) NOT NULL,
                             DT_APROV        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                             STTS_TRAT       VARCHAR2(20) DEFAULT 'aguardando' NOT NULL,
                             OBSERVACOES     VARCHAR2(300),

                             CONSTRAINT FK_PAC_PESS FOREIGN KEY (ID_PESSOA)
                                 REFERENCES TB_PESSOA(ID_PESSOA),

                             CONSTRAINT FK_PAC_TRIAG FOREIGN KEY (ID_TRIAGEM)
                                 REFERENCES TB_TRIAGEM(ID_TRIAGEM),

                             CONSTRAINT CHK_PAC_IDADE CHECK (IDADE BETWEEN 11 AND 17),
                             CONSTRAINT CHK_PAC_STTS CHECK (STTS_TRAT IN ('aguardando','em_tratamento','concluido','cancelado'))
);


-- =============================================================
-- CREATE TB_DENTISTA
-- Dentistas voluntarios disponiveis para encaminhamento.
-- Regra principal: disponivel quando STTS_DENT = ativo e ATIVOS < CAP_MENSAL.
-- =============================================================

CREATE TABLE TB_DENTISTA (
                             ID_DENTISTA     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             ID_ENDERECO     NUMBER NOT NULL,
                             NOME            VARCHAR2(120) NOT NULL,
                             CRO             VARCHAR2(20) NOT NULL UNIQUE,
                             EMAIL           VARCHAR2(120),
                             TELEFONE        VARCHAR2(20) NOT NULL,
                             STTS_DENT       VARCHAR2(10) DEFAULT 'ativo' NOT NULL,
                             CAP_MENSAL      NUMBER(3) DEFAULT 0 NOT NULL,
                             ATIVOS          NUMBER(3) DEFAULT 0 NOT NULL,
                             DATA_CADASTRO   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                             OBSERVACOES     VARCHAR2(300),

                             CONSTRAINT FK_DENT_END FOREIGN KEY (ID_ENDERECO)
                                 REFERENCES TB_ENDERECO(ID_ENDERECO),

                             CONSTRAINT CHK_DENT_STATUS CHECK (STTS_DENT IN ('ativo','inativo')),
                             CONSTRAINT CHK_DENT_CAP CHECK (CAP_MENSAL >= 0),
                             CONSTRAINT CHK_DENT_ATIVOS CHECK (ATIVOS >= 0),
                             CONSTRAINT CHK_DENT_CAP_ATV CHECK (ATIVOS <= CAP_MENSAL)
);


-- =============================================================
-- CREATE TB_ESPECIALIDADE
-- Especialidades odontologicas associadas aos dentistas.
-- =============================================================

CREATE TABLE TB_ESPECIALIDADE (
                                  ID_ESPECIALIDADE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  NOME             VARCHAR2(80) NOT NULL UNIQUE,
                                  DESCRICAO        VARCHAR2(200),
                                  STATUS_ESP       VARCHAR2(10) DEFAULT 'ativa' NOT NULL,

                                  CONSTRAINT CHK_ESP_STATUS CHECK (STATUS_ESP IN ('ativa','inativa'))
);


-- =============================================================
-- CREATE TB_DENTISTA_ESPECIALIDADE
-- Relacao N:N entre dentistas e especialidades.
-- =============================================================

CREATE TABLE TB_DENTISTA_ESPECIALIDADE (
                                           ID_DENTISTA       NUMBER NOT NULL,
                                           ID_ESPECIALIDADE  NUMBER NOT NULL,

                                           CONSTRAINT PK_DENT_ESP PRIMARY KEY (ID_DENTISTA, ID_ESPECIALIDADE),

                                           CONSTRAINT FK_DE_DENT FOREIGN KEY (ID_DENTISTA)
                                               REFERENCES TB_DENTISTA(ID_DENTISTA),

                                           CONSTRAINT FK_DE_ESP FOREIGN KEY (ID_ESPECIALIDADE)
                                               REFERENCES TB_ESPECIALIDADE(ID_ESPECIALIDADE)
);


-- =============================================================
-- CREATE TB_ENCAMINHAMENTO
-- Vinculo paciente-dentista.
-- Sustenta match automatico/manual, distancia e follow-up.
-- =============================================================

CREATE TABLE TB_ENCAMINHAMENTO (
                                   ID_ENCAMINHAMENTO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   ID_PACIENTE       NUMBER NOT NULL,
                                   ID_DENTISTA       NUMBER NOT NULL,
                                   ID_TRIAGEM        NUMBER NOT NULL,
                                   DT_ENCAM          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                                   PREV_FOLLOW       TIMESTAMP NOT NULL,
                                   STTS_ENCAM        VARCHAR2(15) DEFAULT 'ativo' NOT NULL,
                                   MATCH_AUTO        CHAR(1) DEFAULT 'S' NOT NULL,
                                   DIST_KM           NUMBER(8,2),
                                   PRIORIDADE        VARCHAR2(10) NOT NULL,
                                   METODO_CALCULO    VARCHAR2(30) DEFAULT 'nao_informado' NOT NULL,
                                   OBSERVACAO        VARCHAR2(400),

                                   CONSTRAINT FK_ENC_PAC FOREIGN KEY (ID_PACIENTE)
                                       REFERENCES TB_PACIENTE(ID_PACIENTE),

                                   CONSTRAINT FK_ENC_DENT FOREIGN KEY (ID_DENTISTA)
                                       REFERENCES TB_DENTISTA(ID_DENTISTA),

                                   CONSTRAINT FK_ENC_TRIAG FOREIGN KEY (ID_TRIAGEM)
                                       REFERENCES TB_TRIAGEM(ID_TRIAGEM),

                                   CONSTRAINT CHK_ENC_STATUS CHECK (STTS_ENCAM IN ('ativo','concluido','cancelado')),
                                   CONSTRAINT CHK_ENC_MATCH CHECK (MATCH_AUTO IN ('S','N')),
                                   CONSTRAINT CHK_ENC_DIST CHECK (DIST_KM IS NULL OR DIST_KM >= 0),
                                   CONSTRAINT CHK_ENC_PRIOR CHECK (PRIORIDADE IN ('baixa','media','alta','urgente')),
                                   CONSTRAINT CHK_ENC_METODO CHECK (METODO_CALCULO IN ('nominatim_haversine','cep_fallback','manual','nao_informado'))
);


-- =============================================================
-- CREATE TB_CONVERSA
-- Estado da conversa omnichannel.
--
-- Regra critica:
-- - cadastro aponta para pessoa;
-- - acomp_paciente aponta para paciente;
-- - acomp_dentista aponta para dentista;
-- - apenas um vinculo contextual pode estar preenchido.
-- =============================================================

CREATE TABLE TB_CONVERSA (
                             ID_CONVERSA     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             CANAL_CONV      VARCHAR2(20) DEFAULT 'telegram' NOT NULL,
                             CONTEXTO        VARCHAR2(20) NOT NULL,
                             TG_THREAD_ID    VARCHAR2(120),
                             ID_PESSOA       NUMBER,
                             ID_PACIENTE     NUMBER,
                             ID_DENTISTA     NUMBER,
                             STTS_CONV       VARCHAR2(15) DEFAULT 'aberta' NOT NULL,
                             NAO_LIDAS       NUMBER(5) DEFAULT 0 NOT NULL,
                             DATA_CRIACAO    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                             DATA_ATUALIZACAO TIMESTAMP,

                             CONSTRAINT FK_CONV_PESS FOREIGN KEY (ID_PESSOA)
                                 REFERENCES TB_PESSOA(ID_PESSOA),

                             CONSTRAINT FK_CONV_PAC FOREIGN KEY (ID_PACIENTE)
                                 REFERENCES TB_PACIENTE(ID_PACIENTE),

                             CONSTRAINT FK_CONV_DENT FOREIGN KEY (ID_DENTISTA)
                                 REFERENCES TB_DENTISTA(ID_DENTISTA),

                             CONSTRAINT CHK_CONV_CANAL CHECK (CANAL_CONV IN ('telegram','web','whatsapp','manual')),
                             CONSTRAINT CHK_CONV_STATUS CHECK (STTS_CONV IN ('aberta','fechada','arquivada')),
                             CONSTRAINT CHK_CONV_NLIDAS CHECK (NAO_LIDAS >= 0),

                             CONSTRAINT CHK_CONV_CTX_FK CHECK (
                                 (CONTEXTO = 'cadastro'
                                     AND ID_PESSOA IS NOT NULL
                                     AND ID_PACIENTE IS NULL
                                     AND ID_DENTISTA IS NULL)
                                     OR
                                 (CONTEXTO = 'acomp_paciente'
                                     AND ID_PESSOA IS NULL
                                     AND ID_PACIENTE IS NOT NULL
                                     AND ID_DENTISTA IS NULL)
                                     OR
                                 (CONTEXTO = 'acomp_dentista'
                                     AND ID_PESSOA IS NULL
                                     AND ID_PACIENTE IS NULL
                                     AND ID_DENTISTA IS NOT NULL)
                                 )
);


-- =============================================================
-- CREATE TB_MENSAGEM
-- Mensagens trocadas no omnichannel.
-- =============================================================

CREATE TABLE TB_MENSAGEM (
                             ID_MENSAGEM     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             ID_CONVERSA     NUMBER NOT NULL,
                             ENVIADO_POR     VARCHAR2(30) NOT NULL,
                             DIRECAO         VARCHAR2(10) NOT NULL,
                             CONTEUDO        VARCHAR2(1000) NOT NULL,
                             TIPO_MENSAGEM   VARCHAR2(10) DEFAULT 'texto' NOT NULL,
                             DATA_ENVIO      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                             LIDA            CHAR(1) DEFAULT 'N' NOT NULL,

                             CONSTRAINT FK_MSG_CONV FOREIGN KEY (ID_CONVERSA)
                                 REFERENCES TB_CONVERSA(ID_CONVERSA),

                             CONSTRAINT CHK_MSG_ENV CHECK (ENVIADO_POR IN ('bot','atendente','paciente','dentista','sistema')),
                             CONSTRAINT CHK_MSG_DIR CHECK (DIRECAO IN ('entrada','saida')),
                             CONSTRAINT CHK_MSG_TIPO CHECK (TIPO_MENSAGEM IN ('texto','audio','imagem','sistema')),
                             CONSTRAINT CHK_MSG_LIDA CHECK (LIDA IN ('S','N'))
);


-- =============================================================
-- CREATE TB_ACOMP_EVENTO
-- Eventos de acompanhamento, follow-up, retorno do dentista e historico.
-- =============================================================

CREATE TABLE TB_ACOMP_EVENTO (
                                 ID_ACOMP_EVENTO  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 ID_ENCAMINHAMENTO NUMBER NOT NULL,
                                 TIPO_EVENTO      VARCHAR2(30) NOT NULL,
                                 DS_EVENTO        VARCHAR2(600) NOT NULL,
                                 ORIGEM           VARCHAR2(20) NOT NULL,
                                 RESUMO_IA        VARCHAR2(1000),
                                 TIPO_MENSAGEM    VARCHAR2(10),
                                 DATA_EVENTO      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                                 CONSTRAINT FK_ACOMP_ENC FOREIGN KEY (ID_ENCAMINHAMENTO)
                                     REFERENCES TB_ENCAMINHAMENTO(ID_ENCAMINHAMENTO),

                                 CONSTRAINT CHK_ACOMP_TIPO CHECK (TIPO_EVENTO IN ('follow_up','retorno_dentista','observacao','mudanca_status','sistema')),
                                 CONSTRAINT CHK_ACOMP_ORIG CHECK (ORIGEM IN ('n8n','bot','atendente','sistema','dentista')),
                                 CONSTRAINT CHK_ACOMP_MSG CHECK (TIPO_MENSAGEM IS NULL OR TIPO_MENSAGEM IN ('texto','audio','imagem','sistema'))
);


-- =============================================================
-- INSERTS DE DADOS INICIAIS
-- Massa pequena, coerente e suficiente para testes manuais.
-- =============================================================


-- Enderecos de pessoas
INSERT INTO TB_ENDERECO (CEP, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, UF, LATITUDE, LONGITUDE)
VALUES ('01001000', 'Praca da Se', '100', NULL, 'Se', 'Sao Paulo', 'SP', -23.5505200, -46.6333080);

INSERT INTO TB_ENDERECO (CEP, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, UF, LATITUDE, LONGITUDE)
VALUES ('01311000', 'Avenida Paulista', '1500', 'Apto 21', 'Bela Vista', 'Sao Paulo', 'SP', -23.5614140, -46.6558810);

INSERT INTO TB_ENDERECO (CEP, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, UF, LATITUDE, LONGITUDE)
VALUES ('04094050', 'Avenida Ibirapuera', '3000', NULL, 'Moema', 'Sao Paulo', 'SP', -23.6090210, -46.6665110);

-- Enderecos de dentistas
INSERT INTO TB_ENDERECO (CEP, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, UF, LATITUDE, LONGITUDE)
VALUES ('05407002', 'Rua Teodoro Sampaio', '800', 'Sala 12', 'Pinheiros', 'Sao Paulo', 'SP', -23.5609980, -46.6808620);

INSERT INTO TB_ENDERECO (CEP, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, UF, LATITUDE, LONGITUDE)
VALUES ('04543011', 'Rua Funchal', '500', 'Conjunto 34', 'Vila Olimpia', 'Sao Paulo', 'SP', -23.5952720, -46.6842950);


-- Colaboradores
INSERT INTO TB_COLABORADOR (NOME, EMAIL, SENHA_HASH, PERFIL, STATUS_COLAB)
VALUES ('Admin Nora', 'admin@nora.com', 'admin123_hash_academico', 'admin', 'ativo');

INSERT INTO TB_COLABORADOR (NOME, EMAIL, SENHA_HASH, PERFIL, STATUS_COLAB)
VALUES ('Atendente Nora', 'atendente@nora.com', 'atendente123_hash_academico', 'atendente', 'ativo');


-- Sessao inicial para teste de token opaco
INSERT INTO TB_COLABORADOR_SESSAO (ID_COLABORADOR, TOKEN, DATA_EXPIRACAO, STATUS_SESSAO)
VALUES (
           (SELECT ID_COLABORADOR FROM TB_COLABORADOR WHERE EMAIL = 'admin@nora.com'),
           'token-academico-admin-001',
           SYSTIMESTAMP + INTERVAL '1' DAY,
           'ativo'
       );


-- Pessoas/leads
INSERT INTO TB_PESSOA (
    ID_ENDERECO, NOME_COMPLETO, CPF, DATA_NASCIMENTO, IDADE, SEXO,
    EMAIL, TELEFONE, TG_CHAT_ID, CANAL_ORIG, STTS_PESS
)
VALUES (
           (SELECT ID_ENDERECO FROM TB_ENDERECO WHERE CEP = '01001000' AND NUMERO = '100'),
           'Ana Silva Santos',
           '11111111111',
           DATE '2011-04-10',
           15,
           'F',
           'ana.santos@email.com',
           '11990000001',
           'tg_ana_001',
           'telegram',
           'aprovada'
       );

INSERT INTO TB_PESSOA (
    ID_ENDERECO, NOME_COMPLETO, CPF, DATA_NASCIMENTO, IDADE, SEXO,
    EMAIL, TELEFONE, TG_CHAT_ID, CANAL_ORIG, STTS_PESS
)
VALUES (
           (SELECT ID_ENDERECO FROM TB_ENDERECO WHERE CEP = '01311000' AND NUMERO = '1500'),
           'Bruno Costa Lima',
           '22222222222',
           DATE '2012-09-20',
           14,
           'M',
           'bruno.lima@email.com',
           '11990000002',
           'tg_bruno_002',
           'telegram',
           'em_triagem'
       );

INSERT INTO TB_PESSOA (
    ID_ENDERECO, NOME_COMPLETO, CPF, DATA_NASCIMENTO, IDADE, SEXO,
    EMAIL, TELEFONE, TG_CHAT_ID, CANAL_ORIG, STTS_PESS
)
VALUES (
           (SELECT ID_ENDERECO FROM TB_ENDERECO WHERE CEP = '04094050' AND NUMERO = '3000'),
           'Carla Mendes Rocha',
           '33333333333',
           DATE '2009-01-15',
           17,
           'F',
           'carla.rocha@email.com',
           '11990000003',
           'tg_carla_003',
           'n8n',
           'reprovada'
       );


-- Dentistas
INSERT INTO TB_DENTISTA (
    ID_ENDERECO, NOME, CRO, EMAIL, TELEFONE, STTS_DENT, CAP_MENSAL, ATIVOS, OBSERVACOES
)
VALUES (
           (SELECT ID_ENDERECO FROM TB_ENDERECO WHERE CEP = '05407002' AND NUMERO = '800'),
           'Dr. Rafael Almeida',
           'CRO-SP-12345',
           'rafael.almeida@clinica.com',
           '1133330001',
           'ativo',
           5,
           2,
           'Dentista voluntario com disponibilidade parcial.'
       );

INSERT INTO TB_DENTISTA (
    ID_ENDERECO, NOME, CRO, EMAIL, TELEFONE, STTS_DENT, CAP_MENSAL, ATIVOS, OBSERVACOES
)
VALUES (
           (SELECT ID_ENDERECO FROM TB_ENDERECO WHERE CEP = '04543011' AND NUMERO = '500'),
           'Dra. Mariana Lopes',
           'CRO-SP-67890',
           'mariana.lopes@clinica.com',
           '1133330002',
           'ativo',
           3,
           3,
           'Dentista voluntaria atualmente sem vagas.'
       );


-- Especialidades
INSERT INTO TB_ESPECIALIDADE (NOME, DESCRICAO, STATUS_ESP)
VALUES ('clinica_geral', 'Atendimento odontologico geral.', 'ativa');

INSERT INTO TB_ESPECIALIDADE (NOME, DESCRICAO, STATUS_ESP)
VALUES ('ortodontia', 'Acompanhamento ortodontico.', 'ativa');

INSERT INTO TB_ESPECIALIDADE (NOME, DESCRICAO, STATUS_ESP)
VALUES ('odontopediatria', 'Atendimento odontologico infantil e adolescente.', 'ativa');


-- Relacao dentista-especialidade
INSERT INTO TB_DENTISTA_ESPECIALIDADE (ID_DENTISTA, ID_ESPECIALIDADE)
VALUES (
           (SELECT ID_DENTISTA FROM TB_DENTISTA WHERE CRO = 'CRO-SP-12345'),
           (SELECT ID_ESPECIALIDADE FROM TB_ESPECIALIDADE WHERE NOME = 'clinica_geral')
       );

INSERT INTO TB_DENTISTA_ESPECIALIDADE (ID_DENTISTA, ID_ESPECIALIDADE)
VALUES (
           (SELECT ID_DENTISTA FROM TB_DENTISTA WHERE CRO = 'CRO-SP-12345'),
           (SELECT ID_ESPECIALIDADE FROM TB_ESPECIALIDADE WHERE NOME = 'odontopediatria')
       );

INSERT INTO TB_DENTISTA_ESPECIALIDADE (ID_DENTISTA, ID_ESPECIALIDADE)
VALUES (
           (SELECT ID_DENTISTA FROM TB_DENTISTA WHERE CRO = 'CRO-SP-67890'),
           (SELECT ID_ESPECIALIDADE FROM TB_ESPECIALIDADE WHERE NOME = 'ortodontia')
       );


-- Triagens
INSERT INTO TB_TRIAGEM (
    ID_PESSOA, IDADE, ELEG_TRIAG, PRIOR_TRIAG, SEXO_PESS,
    PROBLEMA_BUCAL, RENDA_FAMILIAR, NIVEL_URG_IA, CONF_IA,
    STTS_TRIAG, DECISAO, OBSERVACOES
)
VALUES (
           (SELECT ID_PESSOA FROM TB_PESSOA WHERE CPF = '11111111111'),
           15,
           'elegivel',
           'urgente',
           'F',
           'Dor intensa e suspeita de infeccao odontologica.',
           'ate_1sm',
           4.6,
           91.50,
           'aprovada',
           'aprovado',
           'Caso aprovado para encaminhamento automatico.'
       );

INSERT INTO TB_TRIAGEM (
    ID_PESSOA, IDADE, ELEG_TRIAG, PRIOR_TRIAG, SEXO_PESS,
    PROBLEMA_BUCAL, RENDA_FAMILIAR, NIVEL_URG_IA, CONF_IA,
    STTS_TRIAG, DECISAO, OBSERVACOES
)
VALUES (
           (SELECT ID_PESSOA FROM TB_PESSOA WHERE CPF = '22222222222'),
           14,
           'elegivel',
           'media',
           'M',
           'Dor moderada ao mastigar.',
           '1_3sm',
           2.4,
           78.00,
           'em_analise',
           'pendente',
           'Aguardando avaliacao do atendente.'
       );

INSERT INTO TB_TRIAGEM (
    ID_PESSOA, IDADE, ELEG_TRIAG, PRIOR_TRIAG, SEXO_PESS,
    PROBLEMA_BUCAL, RENDA_FAMILIAR, NIVEL_URG_IA, CONF_IA,
    STTS_TRIAG, DECISAO, OBSERVACOES
)
VALUES (
           (SELECT ID_PESSOA FROM TB_PESSOA WHERE CPF = '33333333333'),
           17,
           'elegivel',
           'baixa',
           'F',
           'Caso sem urgencia no momento.',
           'acima_3sm',
           1.2,
           70.00,
           'reprovada',
           'reprovado',
           'Caso reprovado por criterio operacional definido na triagem.'
       );


-- Paciente derivado da triagem aprovada
INSERT INTO TB_PACIENTE (ID_PESSOA, ID_TRIAGEM, IDADE, STTS_TRAT, OBSERVACOES)
VALUES (
           (SELECT ID_PESSOA FROM TB_PESSOA WHERE CPF = '11111111111'),
           (SELECT ID_TRIAGEM FROM TB_TRIAGEM
            WHERE ID_PESSOA = (SELECT ID_PESSOA FROM TB_PESSOA WHERE CPF = '11111111111')),
           15,
           'em_tratamento',
           'Paciente criado a partir de triagem aprovada.'
       );


-- Encaminhamento ativo
INSERT INTO TB_ENCAMINHAMENTO (
    ID_PACIENTE, ID_DENTISTA, ID_TRIAGEM, DT_ENCAM, PREV_FOLLOW,
    STTS_ENCAM, MATCH_AUTO, DIST_KM, PRIORIDADE, METODO_CALCULO, OBSERVACAO
)
VALUES (
           (SELECT ID_PACIENTE FROM TB_PACIENTE
            WHERE ID_PESSOA = (SELECT ID_PESSOA FROM TB_PESSOA WHERE CPF = '11111111111')),
           (SELECT ID_DENTISTA FROM TB_DENTISTA WHERE CRO = 'CRO-SP-12345'),
           (SELECT ID_TRIAGEM FROM TB_TRIAGEM
            WHERE ID_PESSOA = (SELECT ID_PESSOA FROM TB_PESSOA WHERE CPF = '11111111111')),
           SYSTIMESTAMP - INTERVAL '5' DAY,
           SYSTIMESTAMP + INTERVAL '10' DAY,
           'ativo',
           'S',
           4.72,
           'urgente',
           'nominatim_haversine',
           'Encaminhamento criado por match automatico.'
       );


-- Conversa de paciente aprovado
INSERT INTO TB_CONVERSA (
    CANAL_CONV, CONTEXTO, TG_THREAD_ID, ID_PESSOA, ID_PACIENTE, ID_DENTISTA, STTS_CONV, NAO_LIDAS
)
VALUES (
           'telegram',
           'acomp_paciente',
           'thread_ana_001',
           NULL,
           (SELECT ID_PACIENTE FROM TB_PACIENTE
            WHERE ID_PESSOA = (SELECT ID_PESSOA FROM TB_PESSOA WHERE CPF = '11111111111')),
           NULL,
           'aberta',
           1
       );

-- Conversa de cadastro/triagem em aberto
INSERT INTO TB_CONVERSA (
    CANAL_CONV, CONTEXTO, TG_THREAD_ID, ID_PESSOA, ID_PACIENTE, ID_DENTISTA, STTS_CONV, NAO_LIDAS
)
VALUES (
           'telegram',
           'cadastro',
           'thread_bruno_002',
           (SELECT ID_PESSOA FROM TB_PESSOA WHERE CPF = '22222222222'),
           NULL,
           NULL,
           'aberta',
           2
       );

-- Conversa com dentista
INSERT INTO TB_CONVERSA (
    CANAL_CONV, CONTEXTO, TG_THREAD_ID, ID_PESSOA, ID_PACIENTE, ID_DENTISTA, STTS_CONV, NAO_LIDAS
)
VALUES (
           'telegram',
           'acomp_dentista',
           'thread_dent_rafael',
           NULL,
           NULL,
           (SELECT ID_DENTISTA FROM TB_DENTISTA WHERE CRO = 'CRO-SP-12345'),
           'aberta',
           0
       );


-- Mensagens
INSERT INTO TB_MENSAGEM (
    ID_CONVERSA, ENVIADO_POR, DIRECAO, CONTEUDO, TIPO_MENSAGEM, LIDA
)
VALUES (
           (SELECT ID_CONVERSA FROM TB_CONVERSA WHERE TG_THREAD_ID = 'thread_ana_001'),
           'bot',
           'saida',
           'Ola Ana, seu caso foi encaminhado para um dentista voluntario.',
           'texto',
           'S'
       );

INSERT INTO TB_MENSAGEM (
    ID_CONVERSA, ENVIADO_POR, DIRECAO, CONTEUDO, TIPO_MENSAGEM, LIDA
)
VALUES (
           (SELECT ID_CONVERSA FROM TB_CONVERSA WHERE TG_THREAD_ID = 'thread_bruno_002'),
           'paciente',
           'entrada',
           'Estou com dor ao mastigar.',
           'texto',
           'N'
       );

INSERT INTO TB_MENSAGEM (
    ID_CONVERSA, ENVIADO_POR, DIRECAO, CONTEUDO, TIPO_MENSAGEM, LIDA
)
VALUES (
           (SELECT ID_CONVERSA FROM TB_CONVERSA WHERE TG_THREAD_ID = 'thread_dent_rafael'),
           'dentista',
           'entrada',
           'Recebi o encaminhamento e vou entrar em contato.',
           'texto',
           'S'
       );


-- Evento de acompanhamento
INSERT INTO TB_ACOMP_EVENTO (
    ID_ENCAMINHAMENTO, TIPO_EVENTO, DS_EVENTO, ORIGEM, RESUMO_IA, TIPO_MENSAGEM
)
VALUES (
           (SELECT ID_ENCAMINHAMENTO FROM TB_ENCAMINHAMENTO
            WHERE ID_PACIENTE = (
                SELECT ID_PACIENTE FROM TB_PACIENTE
                WHERE ID_PESSOA = (SELECT ID_PESSOA FROM TB_PESSOA WHERE CPF = '11111111111')
            )
           ),
           'follow_up',
           'Follow-up inicial registrado para acompanhar contato do dentista.',
           'sistema',
           'Evento inicial criado para testar timeline de acompanhamento.',
           'sistema'
       );


COMMIT;


-- =============================================================
-- CONSULTAS DE VALIDACAO
-- =============================================================


-- 1. Contar registros por tabela
SELECT 'TB_ENDERECO' AS TABELA, COUNT(*) AS TOTAL FROM TB_ENDERECO
UNION ALL
SELECT 'TB_COLABORADOR', COUNT(*) FROM TB_COLABORADOR
UNION ALL
SELECT 'TB_COLABORADOR_SESSAO', COUNT(*) FROM TB_COLABORADOR_SESSAO
UNION ALL
SELECT 'TB_PESSOA', COUNT(*) FROM TB_PESSOA
UNION ALL
SELECT 'TB_TRIAGEM', COUNT(*) FROM TB_TRIAGEM
UNION ALL
SELECT 'TB_PACIENTE', COUNT(*) FROM TB_PACIENTE
UNION ALL
SELECT 'TB_DENTISTA', COUNT(*) FROM TB_DENTISTA
UNION ALL
SELECT 'TB_ESPECIALIDADE', COUNT(*) FROM TB_ESPECIALIDADE
UNION ALL
SELECT 'TB_DENTISTA_ESPECIALIDADE', COUNT(*) FROM TB_DENTISTA_ESPECIALIDADE
UNION ALL
SELECT 'TB_ENCAMINHAMENTO', COUNT(*) FROM TB_ENCAMINHAMENTO
UNION ALL
SELECT 'TB_CONVERSA', COUNT(*) FROM TB_CONVERSA
UNION ALL
SELECT 'TB_MENSAGEM', COUNT(*) FROM TB_MENSAGEM
UNION ALL
SELECT 'TB_ACOMP_EVENTO', COUNT(*) FROM TB_ACOMP_EVENTO;


-- 2. Listar triagens por status
SELECT STTS_TRIAG, COUNT(*) AS TOTAL
FROM TB_TRIAGEM
GROUP BY STTS_TRIAG
ORDER BY STTS_TRIAG;


-- 3. Listar dentistas disponiveis
SELECT
    D.ID_DENTISTA,
    D.NOME,
    D.CRO,
    D.STTS_DENT,
    D.CAP_MENSAL,
    D.ATIVOS,
    E.BAIRRO,
    E.CIDADE,
    E.UF
FROM TB_DENTISTA D
         JOIN TB_ENDERECO E ON E.ID_ENDERECO = D.ID_ENDERECO
WHERE D.STTS_DENT = 'ativo'
  AND D.ATIVOS < D.CAP_MENSAL;


-- 4. Listar conversas por contexto
SELECT CONTEXTO, COUNT(*) AS TOTAL
FROM TB_CONVERSA
GROUP BY CONTEXTO
ORDER BY CONTEXTO;


-- 5. Listar encaminhamentos ativos
SELECT
    ENC.ID_ENCAMINHAMENTO,
    P.NOME_COMPLETO AS PACIENTE,
    D.NOME AS DENTISTA,
    ENC.STTS_ENCAM,
    ENC.PRIORIDADE,
    ENC.MATCH_AUTO,
    ENC.DIST_KM,
    ENC.PREV_FOLLOW
FROM TB_ENCAMINHAMENTO ENC
         JOIN TB_PACIENTE PAC ON PAC.ID_PACIENTE = ENC.ID_PACIENTE
         JOIN TB_PESSOA P ON P.ID_PESSOA = PAC.ID_PESSOA
         JOIN TB_DENTISTA D ON D.ID_DENTISTA = ENC.ID_DENTISTA
WHERE ENC.STTS_ENCAM = 'ativo';


-- 6. Testar relacionamento pessoa -> triagem
SELECT
    P.ID_PESSOA,
    P.NOME_COMPLETO,
    P.STTS_PESS,
    T.ID_TRIAGEM,
    T.ELEG_TRIAG,
    T.PRIOR_TRIAG,
    T.STTS_TRIAG,
    T.DECISAO
FROM TB_PESSOA P
         LEFT JOIN TB_TRIAGEM T ON T.ID_PESSOA = P.ID_PESSOA
ORDER BY P.ID_PESSOA;


-- 7. Testar relacionamento paciente -> encaminhamento -> dentista
SELECT
    PAC.ID_PACIENTE,
    P.NOME_COMPLETO AS PACIENTE,
    PAC.STTS_TRAT,
    ENC.ID_ENCAMINHAMENTO,
    ENC.STTS_ENCAM,
    D.NOME AS DENTISTA,
    D.CRO
FROM TB_PACIENTE PAC
         JOIN TB_PESSOA P ON P.ID_PESSOA = PAC.ID_PESSOA
         LEFT JOIN TB_ENCAMINHAMENTO ENC ON ENC.ID_PACIENTE = PAC.ID_PACIENTE
         LEFT JOIN TB_DENTISTA D ON D.ID_DENTISTA = ENC.ID_DENTISTA;


-- 8. Testar mensagens por conversa
SELECT
    C.ID_CONVERSA,
    C.CONTEXTO,
    C.TG_THREAD_ID,
    M.ID_MENSAGEM,
    M.ENVIADO_POR,
    M.DIRECAO,
    M.TIPO_MENSAGEM,
    M.CONTEUDO,
    M.LIDA,
    M.DATA_ENVIO
FROM TB_CONVERSA C
         JOIN TB_MENSAGEM M ON M.ID_CONVERSA = C.ID_CONVERSA
ORDER BY C.ID_CONVERSA, M.DATA_ENVIO;


-- 9. Testar eventos por encaminhamento
SELECT
    ENC.ID_ENCAMINHAMENTO,
    P.NOME_COMPLETO AS PACIENTE,
    D.NOME AS DENTISTA,
    EV.TIPO_EVENTO,
    EV.ORIGEM,
    EV.DS_EVENTO,
    EV.DATA_EVENTO
FROM TB_ACOMP_EVENTO EV
         JOIN TB_ENCAMINHAMENTO ENC ON ENC.ID_ENCAMINHAMENTO = EV.ID_ENCAMINHAMENTO
         JOIN TB_PACIENTE PAC ON PAC.ID_PACIENTE = ENC.ID_PACIENTE
         JOIN TB_PESSOA P ON P.ID_PESSOA = PAC.ID_PESSOA
         JOIN TB_DENTISTA D ON D.ID_DENTISTA = ENC.ID_DENTISTA;


-- 10. Metricas basicas para dashboard
SELECT COUNT(*) AS TOTAL_LEADS FROM TB_PESSOA;

SELECT COUNT(*) AS TOTAL_PACIENTES FROM TB_PACIENTE;

SELECT COUNT(*) AS TOTAL_ENCAMINHAMENTOS_ATIVOS
FROM TB_ENCAMINHAMENTO
WHERE STTS_ENCAM = 'ativo';

SELECT CANAL_ORIG, COUNT(*) AS TOTAL
FROM TB_PESSOA
GROUP BY CANAL_ORIG;

SELECT E.BAIRRO, E.CIDADE, E.UF, COUNT(*) AS TOTAL_PESSOAS
FROM TB_PESSOA P
         JOIN TB_ENDERECO E ON E.ID_ENDERECO = P.ID_ENDERECO
GROUP BY E.BAIRRO, E.CIDADE, E.UF
ORDER BY TOTAL_PESSOAS DESC;